version: "3.5"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - .:app
      - /app/node_modules
    ports:
      - '3000:3000'